-- ═════════════════════════════════════════════════════════════════════════════
-- MIGRATION: Clinic-First Model Implementation
-- 
-- Creates tables for:
--   1. clinic_invite_tokens - Invites for professionals to join clinics
--   2. clinic_memberships - Track user-clinic relationships with roles
-- 
-- Also adds RLS policies for clinic_id isolation
-- ═════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: clinic_invite_tokens
-- 
-- Stores invite tokens generated by clinic admins to invite professionals
-- Token is single-use and expires after 48 hours
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.clinic_invite_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  invited_email text NOT NULL,
  role text DEFAULT 'doctor'::text,
  metadata jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + interval '48 hours'),
  used_at timestamp with time zone,
  used_by uuid,
  
  CONSTRAINT clinic_invite_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_invite_tokens_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinic_invite_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT clinic_invite_tokens_used_by_fkey FOREIGN KEY (used_by) REFERENCES auth.users(id),
  CONSTRAINT clinic_invite_tokens_token_unique UNIQUE (token)
);

-- Index for fast token lookup
CREATE INDEX IF NOT EXISTS idx_clinic_invite_tokens_token ON public.clinic_invite_tokens(token);
CREATE INDEX IF NOT EXISTS idx_clinic_invite_tokens_clinic_id ON public.clinic_invite_tokens(clinic_id);
CREATE INDEX IF NOT EXISTS idx_clinic_invite_tokens_invited_email ON public.clinic_invite_tokens(invited_email);
CREATE INDEX IF NOT EXISTS idx_clinic_invite_tokens_expires_at ON public.clinic_invite_tokens(expires_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: clinic_memberships
-- 
-- Maps users to clinics with specific roles
-- Replaces having clinic_id scattered across users table
-- Enables multi-clinic support (user can belong to multiple clinics)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.clinic_memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'doctor'::text,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  active boolean NOT NULL DEFAULT true,
  metadata jsonb,
  
  CONSTRAINT clinic_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_memberships_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinic_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT clinic_memberships_unique_user_clinic UNIQUE (clinic_id, user_id)
);

-- Index for querying user's clinics
CREATE INDEX IF NOT EXISTS idx_clinic_memberships_user_id ON public.clinic_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_clinic_memberships_clinic_id ON public.clinic_memberships(clinic_id);
CREATE INDEX IF NOT EXISTS idx_clinic_memberships_role ON public.clinic_memberships(role);

-- ═════════════════════════════════════════════════════════════════════════════
-- RLS POLICIES: clinic_invite_tokens
-- ═════════════════════════════════════════════════════════════════════════════

-- Enable RLS
ALTER TABLE public.clinic_invite_tokens ENABLE ROW LEVEL SECURITY;

-- Anyone can create an invite (will be validated by business logic in Edge Function)
CREATE POLICY "Allow clinic defaults to create invites"
  ON public.clinic_invite_tokens
  FOR INSERT
  USING (true);

-- Clinic admins can view invites they created
CREATE POLICY "Clinic admins can view invites"
  ON public.clinic_invite_tokens
  FOR SELECT
  USING (
    auth.uid() = created_by OR
    -- Or user is clinic admin
    EXISTS (
      SELECT 1 FROM public.clinic_memberships cm
      WHERE cm.clinic_id = clinic_invite_tokens.clinic_id
        AND cm.user_id = auth.uid()
        AND cm.role = 'admin'
        AND cm.active = true
    )
  );

-- ═════════════════════════════════════════════════════════════════════════════
-- RLS POLICIES: clinic_memberships
-- ═════════════════════════════════════════════════════════════════════════════

-- Enable RLS
ALTER TABLE public.clinic_memberships ENABLE ROW LEVEL SECURITY;

-- Users can view their own memberships
CREATE POLICY "Users can view own memberships"
  ON public.clinic_memberships
  FOR SELECT
  USING (auth.uid() = user_id);

-- Clinic admins can view clinic memberships
CREATE POLICY "Clinic admins can view memberships"
  ON public.clinic_memberships
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.clinic_memberships cm_admin
      WHERE cm_admin.clinic_id = clinic_memberships.clinic_id
        AND cm_admin.user_id = auth.uid()
        AND cm_admin.role = 'admin'
        AND cm_admin.active = true
    )
  );

-- Clinic admins can manage memberships
CREATE POLICY "Clinic admins can manage memberships"
  ON public.clinic_memberships
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.clinic_memberships cm_admin
      WHERE cm_admin.clinic_id = clinic_memberships.clinic_id
        AND cm_admin.user_id = auth.uid()
        AND cm_admin.role = 'admin'
        AND cm_admin.active = true
    )
  );

-- ═════════════════════════════════════════════════════════════════════════════
-- RLS POLICIES UPDATE: All data tables (patients, appointments, etc)
-- 
-- Add clinic_id isolation to prevent data leakage between clinics
-- ═════════════════════════════════════════════════════════════════════════════

-- PATIENTS: Users can only see patients from their clinics
DROP POLICY IF EXISTS "Users can view own patients" ON public.patients;
CREATE POLICY "Users can view clinic patients"
  ON public.patients
  FOR SELECT
  USING (
    -- User is owner (old system) OR
    auth.uid() = owner_id OR
    -- User is member of the clinic and clinic_id matches
    (
      clinic_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM public.clinic_memberships cm
        WHERE cm.clinic_id = patients.clinic_id
          AND cm.user_id = auth.uid()
          AND cm.active = true
      )
    )
  );

-- APPOINTMENTS: Users can only see appointments from their clinics
DROP POLICY IF EXISTS "Users can view own appointments" ON public.appointments;
CREATE POLICY "Users can view clinic appointments"
  ON public.appointments
  FOR SELECT
  USING (
    -- User is owner (old system) OR
    auth.uid() = owner_id OR
    -- User is member of the clinic and clinic_id matches
    (
      clinic_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM public.clinic_memberships cm
        WHERE cm.clinic_id = appointments.clinic_id
          AND cm.user_id = auth.uid()
          AND cm.active = true
      )
    )
  );

-- MEDICAL_RECORDS: Users can only see records from their clinics
DROP POLICY IF EXISTS "Users can view own records" ON public.medical_records;
CREATE POLICY "Users can view clinic records"
  ON public.medical_records
  FOR SELECT
  USING (
    -- User is owner (old system) OR
    auth.uid() = owner_id OR
    -- User is member of the clinic and clinic_id matches
    (
      clinic_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM public.clinic_memberships cm
        WHERE cm.clinic_id = medical_records.clinic_id
          AND cm.user_id = auth.uid()
          AND cm.active = true
      )
    )
  );

-- Similar policies should be applied to:
-- - exams
-- - stock_items
-- - financial_billings
-- - financial_payments
-- - financial_receivables
-- - financial_payables
-- - financial_glosas
-- - insurance
-- - communication_messages
-- - communication_campaigns
-- - queue_entries
-- - telemedicine_sessions
-- - notifications
-- - protocols
-- - app_templates
-- - audit_log
-- - clinic_rooms
-- (Pattern: add clinic isolation check to SELECT/UPDATE/DELETE policies)

-- ═════════════════════════════════════════════════════════════════════════════
-- HELPER FUNCTIONS
-- ═════════════════════════════════════════════════════════════════════════════

-- Get all clinics for current user
CREATE OR REPLACE FUNCTION public.user_clinics()
RETURNS TABLE(id uuid, name text, cnpj text, email text, phone text) AS $$
BEGIN
  RETURN QUERY
  SELECT c.id, c.name, c.cnpj, c.email, c.phone
  FROM public.clinics c
  INNER JOIN public.clinic_memberships cm ON cm.clinic_id = c.id
  WHERE cm.user_id = auth.uid() AND cm.active = true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check if user is clinic admin
CREATE OR REPLACE FUNCTION public.is_clinic_admin(clinic_id uuid)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.clinic_memberships
    WHERE clinic_id = $1
      AND user_id = auth.uid()
      AND role = 'admin'
      AND active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get user's role in clinic
CREATE OR REPLACE FUNCTION public.user_clinic_role(clinic_id uuid)
RETURNS text AS $$
BEGIN
  RETURN (
    SELECT role FROM public.clinic_memberships
    WHERE clinic_id = $1
      AND user_id = auth.uid()
      AND active = true
    LIMIT 1
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
